### PR TITLE
Address ISLANDORA-1193.

### PR DESCRIPTION
**Pull request by mjordan**

### CODE REVIEW

**Comment by mjordan** [comment]
OK, will add that in a bit. Maybe as an inline comment in the plugin?

**Comment by mjordan** [comment]
Sure, but would it save some space to just point to the official docs on the differences between the various types of FOXML context (which I'm having a hard time finding - got https://wiki.duraspace.org/display/FEDORA37/fedora-export but not a lot more).

**Comment by mjordan** [comment]
Sure, let me know when it's ready and I'll link to it.

**Comment by barmintor** [comment]
https://wiki.duraspace.org/display/FEDORA38/REST+API
https://wiki.duraspace.org/display/FEDORA37/REST+API#RESTAPI-export

**Comment by mjordan** [comment]
@barmintor awesome thanks.

**Pull request merged**
