### PR TITLE
ISLANDORA-2064 better context for access checks.

### PR DESCRIPTION
**Pull request by rosiel**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2064

For the release PR see #49

One of a bajillion pull requests.

# What does this Pull Request do?

Add more context to access check, permitting overrides.

# What's new?

* Use `islandora_object_access()` instead of `user_access()` for access control to allow things to be influenced from our access hooks.

# How should this be tested?

Primarily, regression testing: Things should work as they did.

Simple test module exposing a block allowing the permissions to be denied via our hooks: https://github.com/adam-vessey/islandora_2064_test

# Additional Notes:
Any additional information that you think would be helpful when reviewing this PR.
* **Does this change require documentation to be updated?** No.
* **Does this change add any new dependencies?** No.
* **Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)?** No.
* **Could this change impact execution of existing code?** Unlikely, but it _is_ possible.

# Interested parties

@mjordan  (as component manager), @adam-vessey  (who did most of these pr's), @DiegoPino  @Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by mjordan** [comment]
I'll ~~smoketet~~ smoketest this and #50.

**Comment by rosiel** [comment]
ping @mjordan - I merged the Travis changes (or perhaps rebased on one branch or the other) so this would turn green. Is ok?

**Review by DiegoPino — APPROVED** [review]
Same as the other @adam-vessey pulls. Thanks!

**Comment by mjordan** [comment]
@rosiel just tested this one and can't see any regression effects. Merging. Is there a release PR as well?

**Comment by DiegoPino** [comment]
@mjordan #49 is the release ones, please merge if you are ok with it. Thanks!

**Comment by mjordan** [comment]
OK, will do.

**Pull request merged**
